#!/usr/bin/env bash
# Pre-dispatch safety check. Run BEFORE creating a story packet.
#
#   scripts/dispatch-preflight.sh <story-id> [remote-url-or-path]
#   scripts/dispatch-preflight.sh 0.1.4
#   scripts/dispatch-preflight.sh 0.1.4 https://github.com/hmcts/ctam-reference-data.git
#
# WHY THIS EXISTS
# Coordination in the control plane is by convention: ONE DISPATCHER AT A TIME. sprint-status.yaml
# is a single file, so two people dispatching at once would conflict on it. This script is the
# backstop for when the convention slips. It answers three questions a human would otherwise have
# to remember to ask, and it is entirely read-only.
#
#   1. Is this story already claimed?    its status in sprint-status.yaml must be `backlog`
#   2. Is someone already building it?   no branch naming this story on the target remote
#   3. Is it even buildable yet?         its epic's `depends_on` must all be `done`
#
# It replaces the `owner` field of the retired per-epic ledger: a remote branch IS the claim, so
# there is no shared state to contend over.
#
# SOURCES (both retired artefacts are gone — see SCP 2026-08-19d):
#   status      _bmad-output/implementation-artifacts/sprint-status.yaml   (generated by BMad)
#   repo + deps the epic file's own frontmatter (`repo:` / `depends_on:`)  — not a dispatch graph
#
# Runnable from anywhere.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATUS_FILE="$REPO_ROOT/_bmad-output/implementation-artifacts/sprint-status.yaml"
EPICS_DIR="$REPO_ROOT/_bmad-output/planning-artifacts/epics"

story="${1:-}"
remote_arg="${2:-}"

if [ -z "$story" ]; then
  echo "usage: $(basename "$0") <story-id> [remote-url-or-path]   e.g. $(basename "$0") 0.1.4" >&2
  exit 2
fi
[ -f "$STATUS_FILE" ] || { echo "error: no sprint-status.yaml at $STATUS_FILE — run bmad-sprint-planning" >&2; exit 1; }

dashed="${story//./-}"                       # 0.1.4 -> 0-1-4
epic_num="${story%.*}"                       # 0.1.4 -> 0.1
epic="epic-${epic_num}"
problems=0
warn() { printf '  \033[33mWARN\033[0m  %s\n' "$1"; }
bad()  { printf '  \033[31mSTOP\033[0m  %s\n' "$1"; problems=$((problems + 1)); }
ok()   { printf '  \033[32mok\033[0m    %s\n' "$1"; }

# Frontmatter field of the epic that owns this story.
epic_field() {
  local num="$1" field="$2" file
  file=$(find "$EPICS_DIR" -name "epic-${num}-*.md" -print -quit 2>/dev/null)
  [ -n "$file" ] || return 1
  awk -v f="^${field}:" '$0 ~ f { sub(/^[^:]*:[[:space:]]*/, ""); sub(/#.*/, ""); print; exit }' "$file"
}

printf '\nPre-dispatch check — story %s (%s)\n\n' "$story" "$epic"

# ---------------------------------------------------------------- 1. is it claimed?
line=$(grep -E "^[[:space:]]*${dashed}-[^:]*:" "$STATUS_FILE" | head -1 || true)
if [ -z "$line" ]; then
  bad "story $story is not in sprint-status.yaml — either the id is wrong, or the epics changed and bmad-sprint-planning needs re-running"
else
  key="${line%%:*}"; key="${key//[[:space:]]/}"
  status="${line##*:}"; status="${status//[[:space:]]/}"
  case "$status" in
    backlog)            ok "status is 'backlog' — free to dispatch  ($key)" ;;
    ready-for-dev)      bad "status is 'ready-for-dev' — a packet already exists. Someone dispatched this; do not dispatch twice." ;;
    in-progress|review) bad "status is '$status' — someone is building this right now." ;;
    done)               bad "status is 'done'." ;;
    *)                  warn "unrecognised status '$status' — check the file by hand." ;;
  esac
fi

# ---------------------------------------------------------------- 2. is someone building it?
repo_names=""
if [ -n "$remote_arg" ]; then
  repo_names="$remote_arg"
else
  repo_field=$(epic_field "$epic_num" repo || true)
  repo_field="${repo_field//[\[\]]/}"
  repo_names=$(printf '%s' "$repo_field" | tr ',' ' ')
fi

if [ -z "${repo_names// /}" ]; then
  warn "no 'repo:' in ${epic}'s frontmatter — add it, or pass the remote as the second argument"
else
  for name in $repo_names; do
    name="${name//[[:space:]]/}"
    [ -z "$name" ] && continue
    case "$name" in
      *://*|/*) remote="$name" ;;
      *)        remote="https://github.com/hmcts/${name}.git" ;;
    esac
    branches=$(git ls-remote --heads "$remote" 2>/dev/null | awk '{print $2}' | sed 's#refs/heads/##' || true)
    if [ -z "$branches" ]; then
      warn "$name — no branches readable (repo may not exist yet, or no access); cannot rule out a claim"
      continue
    fi
    claimed=$(printf '%s\n' "$branches" | grep -E "(^|[/-])(${story}|${dashed})([/-]|$)" || true)
    if [ -n "$claimed" ]; then
      bad "$name — a branch already names this story, so someone has claimed it:"
      printf '%s\n' "$claimed" | sed 's/^/          /'
    else
      ok "$name — no branch names this story"
    fi
  done
fi

# ---------------------------------------------------------------- 3. is it buildable?
blocking=$(epic_field "$epic_num" depends_on || true)
blocking="${blocking//[\[\]]/}"
if [ -z "${blocking// /}" ]; then
  ok "no prerequisites recorded for $epic"
else
  for d in $(printf '%s' "$blocking" | tr ',' ' '); do
    d="${d//[[:space:]]/}"
    [ -z "$d" ] && continue
    dline=$(grep -E "^[[:space:]]*${d}:" "$STATUS_FILE" | head -1 || true)
    if [ -z "$dline" ]; then
      warn "prerequisite '$d' is not in sprint-status.yaml — check the id, or re-run bmad-sprint-planning"
    else
      dstatus="${dline##*:}"; dstatus="${dstatus//[[:space:]]/}"
      if [ "$dstatus" = "done" ]; then
        ok "prerequisite $d is done"
      else
        bad "prerequisite $d is '$dstatus', not 'done'"
      fi
    fi
  done
fi

printf '\n'
if [ "$problems" -gt 0 ]; then
  printf '\033[31m%d blocker(s) — do not dispatch.\033[0m\n' "$problems"
  exit 1
fi
printf '\033[32mClear to dispatch.\033[0m One dispatcher at a time, and set this story to\n'
printf 'ready-for-dev in sprint-status.yaml in the same change as the packet.\n'
