#!/usr/bin/env bash
# Pre-dispatch safety check. Run BEFORE creating a story packet.
#
#   scripts/dispatch-preflight.sh <story-id> [remote-url-or-path]
#   scripts/dispatch-preflight.sh 0.1.4
#   scripts/dispatch-preflight.sh 0.1.4 https://github.com/hmcts/ctam-reference-data.git
#
# WHY THIS EXISTS
# Coordination in the control plane is by convention: ONE DISPATCHER AT A TIME. sprint-status.yaml
# is a single file, so two people dispatching at once would conflict on it. This script is the
# backstop for when the convention slips. It answers four questions a human would otherwise have
# to remember to ask, and it is entirely read-only.
#
#   1. Is this story already claimed?    its status in sprint-status.yaml must be `backlog`
#   2. Is someone already building it?   no branch naming this story on the target remote
#   3. Is it even buildable yet?         its epic's `depends_on` must all be `done`
#   4. Is it its turn?                   no EARLIER story in the same epic is still `backlog`
#                                        (stories in an epic are ordered; no field records that,
#                                        so the order in sprint-status.yaml is the dependency)
#
# It replaces the `owner` field of the retired per-epic ledger: a remote branch IS the claim, so
# there is no shared state to contend over.
#
# SOURCES (both retired artefacts are gone — see SCP 2026-08-19d):
#   status      _bmad-output/implementation-artifacts/sprint-status.yaml   (generated by BMad)
#   repo + deps the epic file's own frontmatter (`repo:` / `depends_on:`)  — not a dispatch graph
#
# Runnable from anywhere.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATUS_FILE="$REPO_ROOT/_bmad-output/implementation-artifacts/sprint-status.yaml"
EPICS_DIR="$REPO_ROOT/_bmad-output/planning-artifacts/epics"

story="${1:-}"
remote_arg="${2:-}"

if [ -z "$story" ]; then
  echo "usage: $(basename "$0") <story-id> [remote-url-or-path]   e.g. $(basename "$0") 0.1.4" >&2
  exit 2
fi
[ -f "$STATUS_FILE" ] || { echo "error: no sprint-status.yaml at $STATUS_FILE — run bmad-sprint-planning" >&2; exit 1; }

dashed="${story//./-}"                       # 0.1.4 -> 0-1-4
epic_num="${story%.*}"                       # 0.1.4 -> 0.1
epic="epic-${epic_num}"
problems=0
warn() { printf '  \033[33mWARN\033[0m  %s\n' "$1"; }
bad()  { printf '  \033[31mSTOP\033[0m  %s\n' "$1"; problems=$((problems + 1)); }
ok()   { printf '  \033[32mok\033[0m    %s\n' "$1"; }

# Frontmatter field of the epic that owns this story.
epic_field() {
  local num="$1" field="$2" file
  file=$(find "$EPICS_DIR" -name "epic-${num}-*.md" -print -quit 2>/dev/null)
  [ -n "$file" ] || return 1
  awk -v f="^${field}:" '$0 ~ f { sub(/^[^:]*:[[:space:]]*/, ""); sub(/#.*/, ""); print; exit }' "$file"
}

printf '\nPre-dispatch check — story %s (%s)\n\n' "$story" "$epic"

# ---------------------------------------------------------------- 1. is it claimed?
line=$(grep -E "^[[:space:]]*${dashed}-[^:]*:" "$STATUS_FILE" | head -1 || true)
if [ -z "$line" ]; then
  bad "story $story is not in sprint-status.yaml — either the id is wrong, or the epics changed and bmad-sprint-planning needs re-running"
else
  key="${line%%:*}"; key="${key//[[:space:]]/}"
  status="${line##*:}"; status="${status//[[:space:]]/}"
  case "$status" in
    backlog)            ok "status is 'backlog' — free to dispatch  ($key)" ;;
    ready-for-dev)      bad "status is 'ready-for-dev' — a packet already exists. Someone dispatched this; do not dispatch twice." ;;
    in-progress|review) bad "status is '$status' — someone is building this right now." ;;
    done)               bad "status is 'done'." ;;
    *)                  warn "unrecognised status '$status' — check the file by hand." ;;
  esac
fi

# ---------------------------------------------------------------- 2. is someone building it?
repo_names=""
if [ -n "$remote_arg" ]; then
  repo_names="$remote_arg"
else
  repo_field=$(epic_field "$epic_num" repo || true)
  repo_field="${repo_field//[\[\]]/}"
  repo_names=$(printf '%s' "$repo_field" | tr ',' ' ')
fi

if [ -z "${repo_names// /}" ]; then
  warn "no 'repo:' in ${epic}'s frontmatter — add it, or pass the remote as the second argument"
else
  for name in $repo_names; do
    name="${name//[[:space:]]/}"
    [ -z "$name" ] && continue
    case "$name" in
      *://*|/*) remote="$name" ;;
      *)        remote="https://github.com/hmcts/${name}.git" ;;
    esac
    branches=$(git ls-remote --heads "$remote" 2>/dev/null | awk '{print $2}' | sed 's#refs/heads/##' || true)
    if [ -z "$branches" ]; then
      warn "$name — no branches readable (repo may not exist yet, or no access); cannot rule out a claim"
      continue
    fi
    claimed=$(printf '%s\n' "$branches" | grep -E "(^|[/-])(${story}|${dashed})([/-]|$)" || true)
    if [ -n "$claimed" ]; then
      bad "$name — a branch already names this story, so someone has claimed it:"
      printf '%s\n' "$claimed" | sed 's/^/          /'
    else
      ok "$name — no branch names this story"
    fi
  done
fi

# ---------------------------------------------------------------- 3. is it buildable?
blocking=$(epic_field "$epic_num" depends_on || true)
blocking="${blocking//[\[\]]/}"
if [ -z "${blocking// /}" ]; then
  ok "no prerequisites recorded for $epic"
else
  for d in $(printf '%s' "$blocking" | tr ',' ' '); do
    d="${d//[[:space:]]/}"
    [ -z "$d" ] && continue
    dline=$(grep -E "^[[:space:]]*${d}:" "$STATUS_FILE" | head -1 || true)
    if [ -z "$dline" ]; then
      warn "prerequisite '$d' is not in sprint-status.yaml — check the id, or re-run bmad-sprint-planning"
    else
      dstatus="${dline##*:}"; dstatus="${dstatus//[[:space:]]/}"
      if [ "$dstatus" = "done" ]; then
        ok "prerequisite $d is done"
      else
        bad "prerequisite $d is '$dstatus', not 'done'"
      fi
    fi
  done
fi

# ---------------------------------------------------------------- 4. is it its turn?
# Stories inside a CTAM epic are ordered by construction — scaffold the repo, then the schema, then
# the ingestion that needs both — and NO field records that ordering. The epic's `depends_on` covers
# epic-to-epic only, so nothing stopped 0.1.4 being dispatched while 0.1.1 had not been built. The
# order in sprint-status.yaml IS the story-level dependency: an earlier sibling still `backlog`
# means the ground this story stands on does not exist yet.
if printf '%s' "$story" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  story_leaf="${story##*.}"
  epic_dashed="${epic_num//./-}"
  siblings=0
  behind=""
  inflight=""
  while IFS= read -r sline; do
    skey="${sline%%:*}"; skey="${skey//[[:space:]]/}"
    sstatus="${sline##*:}"; sstatus="${sstatus//[[:space:]]/}"
    leaf=$(printf '%s' "$skey" | awk -F- '{print $3}')
    case "$leaf" in ''|*[!0-9]*) continue ;; esac
    [ "$leaf" -lt "$story_leaf" ] || continue
    siblings=$((siblings + 1))
    case "$sstatus" in
      done)    ;;
      backlog) behind="$behind $skey" ;;
      *)       inflight="$inflight $skey" ;;
    esac
  done < <(grep -E "^[[:space:]]*${epic_dashed}-[0-9]+-[^:]*:" "$STATUS_FILE")

  if [ "$siblings" -eq 0 ]; then
    ok "no earlier stories in $epic — this is the first"
  elif [ -n "${behind// /}" ]; then
    bad "earlier stories in $epic are still 'backlog' — this story's ground is not built yet:"
    for b in $behind; do printf '          %s\n' "$b"; done
    printf '          %s\n' "(stories in a CTAM epic are ordered; dispatch in order, or say why not)"
  elif [ -n "${inflight// /}" ]; then
    warn "earlier stories in $epic are in flight, not done:$inflight"
    warn "parallel dispatch inside one epic is a judgement call — check the packets cannot collide"
  else
    ok "every earlier story in $epic is done"
  fi
else
  warn "story id '$story' is not <phase>.<epic>.<story> — skipping the intra-epic ordering check"
fi

printf '\n'
if [ "$problems" -gt 0 ]; then
  printf '\033[31m%d blocker(s) — do not dispatch.\033[0m\n' "$problems"
  exit 1
fi
printf '\033[32mClear to dispatch.\033[0m One dispatcher at a time. Next:\n'
printf '  1. in the target repo:  git switch main && git pull\n'
printf '  2.                      git switch -c story/%s\n' "$story"
printf '  3. land the packet at   docs/stories/%s.md, commit, then push -u\n' "$story"
printf '     (the pushed branch is the claim — this check reads the remote)\n'
printf '  4. set %s to ready-for-dev in sprint-status.yaml\n' "$story"
printf '  Do not open the PR: that is the human gate.\n'
